# Generated by Django 5.1.2 on 2024-11-07 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noivos', '0003_presentes_reservado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='noivos.convidados')),
            ],
        ),
    ]
