# Generated by Django 5.1.2 on 2024-11-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhantes',
            name='nome_acompanhante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
